create table tb_categoria (id int8 generated by default as identity, nome varchar(255), primary key (id));
create table tb_despesas (id int8 generated by default as identity, date date, media_fatura int4, total float8, ultima_fatura int4, categoria_id int8, primary key (id));
alter table if exists tb_despesas add constraint FKkhqu0p5f2knas7wvhgkkbewye foreign key (categoria_id) references tb_categoria;

